# .github/workflows/auto-test.yml

name: Test This Project

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout this repository
        uses: actions/checkout@v4

      - name: set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: install packages
        run: npm ci

      # テストを実行
      - name: run vitest
        run: npm test -- --run

      # カバレッジを出力
      - name: run coverage and test
        run: npm run coverage -- --run

      - name: uplaod coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/